version: "3.9"
   
services:
  db:
    image: postgres:11.5
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
    - POSTGRES_DB_NAME=postgres
    - POSTGRES_DB_USER=postgres
    - POSTGRES_DB_PASSWORD=postgres
    - POSTGRES_DB_HOST=db
    - POSTGRES_DB_PORT=5432
    - POSTGRES_DB_SCHEMA=public
    - GOOGLE_KEY=AIzaSyB79Cn6-IfuSAqz6r3xalDL6UU0UQTNS0E
    command: 
    - python manage.py createcachetable && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    # volumes:
      # - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
