# Generated by Django 3.1.7 on 2021-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubedata",
            name="thumnail_url",
        ),
        migrations.AddField(
            model_name="youtubedata",
            name="channel_title",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="youtubedata",
            name="thumnail_urls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
